[package]
name = 'rujak'
license = 'MIT'
edition = '2021'
version = '0.1.0'
description = 'benchmarking lib/cli'

[dependencies]
clap = { version = '3', default-features = false, features = [
  'std',
  'env',
  'cargo',
  'color',
] }
